# Generated by Django 4.2.2 on 2023-09-25 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='top_images/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='tos_images/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_s_p', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('add_title', models.TextField()),
                ('image', models.ImageField(upload_to='adds_images/%Y/%m/')),
                ('description', models.TextField()),
                ('training_rooms', models.TextField()),
                ('adress', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('phone_number2', models.CharField(max_length=100)),
                ('site1', models.CharField(max_length=100)),
                ('site2', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('priceList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.pricelist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
